/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    GithubIcon: typeof import('./src/components/icons/GithubIcon.vue')['default']
    HeaderItem: typeof import('./src/components/HeaderItem.vue')['default']
    MelodyIcon: typeof import('./src/components/icons/MelodyIcon.vue')['default']
    OverlayItem: typeof import('./src/components/OverlayItem.vue')['default']
    PreloadedImage: typeof import('./src/components/PreloadedImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpotifyAppIcon: typeof import('./src/components/icons/SpotifyAppIcon.vue')['default']
    SpotifyIcon: typeof import('./src/components/icons/SpotifyIcon.vue')['default']
  }
}
